// <auto-generated />
using BlazorShop.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711181339_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorShop.Api.Entities.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.CarrinhoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("CarrinhoItens");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconCSS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconCSS = "fas fa-tv",
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            IconCSS = "fas fa-tshirt",
                            Nome = "Roupas"
                        },
                        new
                        {
                            Id = 3,
                            IconCSS = "fas fa-book",
                            Nome = "Livros"
                        },
                        new
                        {
                            Id = 4,
                            IconCSS = "fas fa-football-ball",
                            Nome = "Esportes"
                        },
                        new
                        {
                            Id = 5,
                            IconCSS = "fas fa-magic",
                            Nome = "Beleza"
                        },
                        new
                        {
                            Id = 6,
                            IconCSS = "fas fa-utensils",
                            Nome = "Alimentos"
                        },
                        new
                        {
                            Id = 7,
                            IconCSS = "fas fa-puzzle-piece",
                            Nome = "Brinquedos"
                        },
                        new
                        {
                            Id = 8,
                            IconCSS = "fas fa-couch",
                            Nome = "Móveis"
                        },
                        new
                        {
                            Id = 9,
                            IconCSS = "fas fa-heartbeat",
                            Nome = "Saúde"
                        },
                        new
                        {
                            Id = 10,
                            IconCSS = "fas fa-car",
                            Nome = "Automóveis"
                        },
                        new
                        {
                            Id = 11,
                            IconCSS = "fas fa-music",
                            Nome = "Música"
                        },
                        new
                        {
                            Id = 12,
                            IconCSS = "fas fa-plane",
                            Nome = "Viagem"
                        },
                        new
                        {
                            Id = 13,
                            IconCSS = "fas fa-home",
                            Nome = "Casa e Jardim"
                        },
                        new
                        {
                            Id = 14,
                            IconCSS = "fas fa-laptop",
                            Nome = "Tecnologia"
                        },
                        new
                        {
                            Id = 15,
                            IconCSS = "fas fa-camera",
                            Nome = "Fotografia"
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Smartphone de última geração",
                            ImagemUrl = "/Imagens/Smartphone/smartphone.png",
                            Nome = "Smartphone",
                            Preco = 1999.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descricao = "Camiseta de algodão",
                            ImagemUrl = "/Imagens/Camiseta/camiseta.png",
                            Nome = "Camiseta",
                            Preco = 49.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descricao = "Livro de programação",
                            ImagemUrl = "/Imagens/Livro/livro.png",
                            Nome = "Livro",
                            Preco = 79.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descricao = "Tênis confortável para corrida",
                            ImagemUrl = "/Imagens/Tenis/tenis.png",
                            Nome = "Tênis de Corrida",
                            Preco = 299.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 14,
                            Descricao = "Notebook de última geração",
                            ImagemUrl = "/Imagens/Notebook/notebook.png",
                            Nome = "Notebook",
                            Preco = 3999.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 15,
                            Descricao = "Câmera profissional para fotografia",
                            ImagemUrl = "/Imagens/Camara/camera.png",
                            Nome = "Câmera Fotográfica",
                            Preco = 2499.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 1,
                            Descricao = "Fone de ouvido com cancelamento de ruído",
                            ImagemUrl = "/Imagens/Fone/fone.png",
                            Nome = "Fone de Ouvido",
                            Preco = 199.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 1,
                            Descricao = "Relógio com monitoramento de atividades físicas",
                            ImagemUrl = "/Imagens/Relogio/relogio.png",
                            Nome = "Relógio Inteligente",
                            Preco = 499.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 8,
                            Descricao = "Cadeira ergonômica para gamers",
                            ImagemUrl = "/Imagens/Cadeira/cadeira.png",
                            Nome = "Cadeira Gamer",
                            Preco = 899.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 4,
                            Descricao = "Bicicleta para trilhas e passeios",
                            ImagemUrl = "/Imagens/Bicicleta/bicicleta.png",
                            Nome = "Bicicleta",
                            Preco = 1499.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 5,
                            Descricao = "Perfume importado de alta qualidade",
                            ImagemUrl = "/Imagens/Perfume/perfume.png",
                            Nome = "Perfume",
                            Preco = 299.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 6,
                            Descricao = "Cafeteira elétrica para café expresso",
                            ImagemUrl = "/Imagens/Cafeteira/cafeteira.png",
                            Nome = "Cafeteira",
                            Preco = 249.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 7,
                            Descricao = "Brinquedo que estimula o aprendizado",
                            ImagemUrl = "/Imagens/Brinquedo/brinquedo.png",
                            Nome = "Brinquedo Educativo",
                            Preco = 79.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 8,
                            Descricao = "Sofá confortável para sala de estar",
                            ImagemUrl = "/Imagens/Sofa/sofa.png",
                            Nome = "Sofá",
                            Preco = 1999.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 13,
                            Descricao = "Aspirador potente para limpeza doméstica",
                            ImagemUrl = "/Imagens/Aspirador/aspirador.png",
                            Nome = "Aspirador de Pó",
                            Preco = 399.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 11,
                            Descricao = "Guitarra de alta qualidade para músicos",
                            ImagemUrl = "/Imagens/Guitarra/guitarra.png",
                            Nome = "Guitarra Elétrica",
                            Preco = 1499.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 12,
                            Descricao = "Mochila resistente para viagens e aventuras",
                            ImagemUrl = "/Imagens/Mochila/mochila.png",
                            Nome = "Mochila de Viagem",
                            Preco = 299.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 1,
                            Descricao = "Tablet de última geração para entretenimento e produtividade",
                            ImagemUrl = "/Imagens/Tablet/tablet.png",
                            Nome = "Tablet",
                            Preco = 1299.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 3,
                            Descricao = "Livro envolvente de ficção para leitura prazerosa",
                            ImagemUrl = "/Imagens/LivroFiccao/livroficcao.png",
                            Nome = "Livro de Ficção",
                            Preco = 59.99m,
                            Quantidade = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 2,
                            Descricao = "Camiseta com estampa moderna e estilosa",
                            ImagemUrl = "/Imagens/CamisetaEstampada/camisetaestampada.png",
                            Nome = "Camiseta Estampada",
                            Preco = 69.99m,
                            Quantidade = 0
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeUsuario = "Gemilso"
                        },
                        new
                        {
                            Id = 2,
                            NomeUsuario = "Gladis"
                        },
                        new
                        {
                            Id = 3,
                            NomeUsuario = "Gustavo"
                        },
                        new
                        {
                            Id = 4,
                            NomeUsuario = "Amalia"
                        },
                        new
                        {
                            Id = 5,
                            NomeUsuario = "Neusa"
                        });
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Carrinho", b =>
                {
                    b.HasOne("BlazorShop.Api.Entities.Usuario", null)
                        .WithOne("Carrinho")
                        .HasForeignKey("BlazorShop.Api.Entities.Carrinho", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.CarrinhoItem", b =>
                {
                    b.HasOne("BlazorShop.Api.Entities.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Api.Entities.Produto", "Produto")
                        .WithMany("Itens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Produto", b =>
                {
                    b.HasOne("BlazorShop.Api.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Produto", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BlazorShop.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Carrinho");
                });
#pragma warning restore 612, 618
        }
    }
}
